SportsStore.WebUI/Models/CartIndexViewModel.cs
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        /// <summary>
        /// instacncja koszyka
        /// </summary>
        public Cart Cart { get; set; }
        /// <summary>
        /// Zwracany adres Url
        /// </summary>
        public string ReturnUrl { get; set; }
    }
}

SportsStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
    /// <summary>
    /// Informacje potrzbne przy stronicowaniu
    /// </summary>
    public class PagingInfo
    {
        /// <summary>
        /// Całkowita ilość przedmiotów 
        /// </summary>
        public int TotalItems { get; set; }
        /// <summary>
        /// Ilość przedmiotów na stronę
        /// </summary>
        public int ItemsPerPage { get; set; }
        /// <summary>
        /// Strona bieżąca
        /// </summary>
        public int CurrentPage { get; set; }
        /// <summary>
        /// Ilość stron
        /// </summary>
        public int TotalPages
        {
            get { return (int)Math.Ceiling((double)TotalItems / ItemsPerPage); }
        }
    }
}

SportsStore.WebUI/Models/ProductsListViewModel.cs
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
    /// <summary>
    /// Klasa View Model opakowująca dane z kolekcji produktów, dane stronicowania
    /// oraz bieżącą kategorię
    /// </summary>
    public class ProductsListViewModel
    {
        /// <summary>
        /// Kolekcja produktów
        /// </summary>
        public IEnumerable<Product> Products { get; set; }
        /// <summary>
        /// Informacje o stronicowaniu
        /// </summary>
        public PagingInfo PagingInfo { get; set; }
        /// <summary>
        /// Bieżąca kategoria filtrowania
        /// </summary>
        public string CurrentCategory{ get; set; }
    }
}

SportsStore.WebUI/Controllers/CartController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository productRepository;
        /// <summary>
        /// Tworzy kontroler 
        /// </summary>
        /// <param name="productRepositoryParam">Repozytroium produktów</param>
        public CartController(IProductRepository productRepositoryParam)
        {
            productRepository = productRepositoryParam;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = GetCart(),
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(int productId, string returnUrl)
        {
            Product product = productRepository.Products.
                FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
                GetCart().AddItem(product, 1);
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(int productId, string returnUrl)
        {
            Product product = productRepository.Products.
                FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
                GetCart().RemoveLine(product);
            return RedirectToAction("Index", new { returnUrl });
        }

        private Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"];
            if (cart == null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }
            return cart;
        }
    }
}

SportsStore.WebUI/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;

namespace SportsStore.WebUI.Controllers
{
    public class NavigationController : Controller
    {
        private IProductRepository productRepository;

        public NavigationController(IProductRepository productRepositoryParam)
        {
            productRepository = productRepositoryParam;
        }

        // GET: Navigation
        public PartialViewResult Menu(string chosenCategory = null)
        {
            ViewBag.SelectedCategory = chosenCategory;
            IEnumerable<string> categories = productRepository.Products.
                Select(prod => prod.Category).
                Distinct().
                OrderBy(cat => cat);
            return PartialView(categories);
        }
    }
}

SportsStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository productRepository;
        public int PageSize = 3;
        /// <summary>
        /// Tworzy kontroler dla modelu produktu
        /// </summary>
        /// <param name="productRepositoryParam">Repozytroium produktów (IEnumerable)</param>
        public ProductController(IProductRepository productRepositoryParam)
        {
            this.productRepository = productRepositoryParam;
        }
        /// <summary>
        /// Metoda zwracająca widok kolekcji produktów wraz z stronicowaniem
        /// Przekazuje do widoku model widoku, zapewniajacy widokowi dostep do danych o stronicowaniu
        /// oraz o kolekcji produktów
        /// </summary>
        /// <returns></returns>
        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = productRepository.Products.
                    Where(p => p.Category == category || category == null).
                    OrderBy(p => p.ProductId).
                    Skip((page - 1) * PageSize).
                    Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                    productRepository.Products.Count() :
                    productRepository.Products.Where(p => p.Category == category).Count()

                },
                CurrentCategory = category
            };
            return View(model);
        }
    }
}

SportsStore.WebUI/Views/Cart/Index.cshtml
@model SportsStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "Sklep sportowy Pablo: Twój Koszyk";
}

<h2>Twój koszyk</h2>
<table class="table">
    <thead>
        <tr>
            <th>Ilość</th>
            <th>Produkt</th>
            <th class="text-right">Cena</th>
            <th class="text-right">Wartość</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Product.Name</td>
                <td class="text-right">@line.Product.Price</td>
                <td class="text-right">@((line.Product.Price * line.Quantity).ToString("c"))</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Razem:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("c");
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
   <a class="btn btn-primary" href="@Model.ReturnUrl">Kontynuuj zakupy</a>
</div>

SportsStore.WebUI/Views/Navigation/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Strona Główna", "List", "Product", null,
    new { @class = "btn btn-block btn-default btn-lg" })
@foreach (var linkCategory in Model)
{
    @Html.RouteLink(linkCategory,
    new
    {
        controller = "Product",
        action = "List",
        category = linkCategory,
        page = 1
    }, new
    {
        @class = "btn btn-block btn-default btn-lg" 
        + (linkCategory == ViewBag.SelectedCategory ? " btn-primary" : "")
    })
}

SportsStore.WebUI/Views/Product/List.cshtml
@model SportsStore.WebUI.Models.ProductsListViewModel

@{
    ViewBag.Title = "Produkty";
}

@foreach (var product in Model.Products)
{
    @Html.Partial("ProductSummary", product); 
}

<div class="pager">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { category = Model.CurrentCategory, page = x}))
</div>

SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProductId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Dodaj do koszyka" />
        </div>
    }

    <span class="lead">
        @Model.Description
    </span>

</div>

SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse " role="navigation">
        <a class="navbar-brand" href="#">Pablo - Sklep Sportowy</a>
    </div>

    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu","Navigation")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>               
    </div>
    
    <footer class="panel-footer">
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</body>



</html>